#!/usr/bin/env python3
"""Create a paragraph and sentence revision ledger from a LaTeX file."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


SECTION_RE = re.compile(r"^\\(section|subsection|subsubsection)\*?\{(.+?)\}")
BEGIN_SKIP_RE = re.compile(r"^\\begin\{(equation|align|table|longtable|figure|center|tabular|minipage|highlights|keywords|abstract)\}")
END_SKIP_RE = re.compile(r"^\\end\{(equation|align|table|longtable|figure|center|tabular|minipage|highlights|keywords|abstract)\}")


@dataclass
class Paragraph:
    section_index: int
    section_title: str
    paragraph_index: int
    start_line: int
    end_line: int
    text: str


def read_text(path: Path) -> str:
    for encoding in ("utf-8", "utf-8-sig", "gb18030", "latin-1"):
        try:
            return path.read_text(encoding=encoding)
        except UnicodeDecodeError:
            continue
    return path.read_text(errors="replace")


def clean_inline_latex(text: str) -> str:
    text = re.sub(r"%.*", "", text)
    text = re.sub(r"\\cite\w*\*?(?:\[[^\]]*\]){0,2}\{[^}]+\}", "[cite]", text)
    text = re.sub(r"\\(?:ref|eqref|autoref|cref|Cref)\{[^}]+\}", "[ref]", text)
    text = re.sub(r"\$[^$]*\$", "[math]", text)
    text = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?(?:\{[^}]*\})?", "", text)
    return re.sub(r"\s+", " ", text).strip()


def split_sentences(text: str) -> list[str]:
    cleaned = clean_inline_latex(text)
    if not cleaned:
        return []
    parts = re.split(r"(?<=[.!?。！？])\s+", cleaned)
    return [part.strip() for part in parts if part.strip()]


def collect_paragraphs(lines: list[str]) -> list[Paragraph]:
    paragraphs: list[Paragraph] = []
    current_section = "Front matter"
    current_section_idx = 0
    paragraph_idx = 0
    buffer: list[tuple[int, str]] = []
    skip_depth = 0

    def flush() -> None:
        nonlocal paragraph_idx, buffer
        if not buffer:
            return
        text = "\n".join(line for _, line in buffer).strip()
        if current_section_idx > 0 and text and not text.startswith("\\"):
            paragraph_idx += 1
            paragraphs.append(
                Paragraph(
                    section_index=current_section_idx,
                    section_title=current_section,
                    paragraph_index=paragraph_idx,
                    start_line=buffer[0][0],
                    end_line=buffer[-1][0],
                    text=text,
                )
            )
        buffer = []

    for line_no, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        section_match = SECTION_RE.match(line)
        if section_match:
            flush()
            current_section_idx += 1
            current_section = section_match.group(2)
            paragraph_idx = 0
            continue

        if BEGIN_SKIP_RE.match(line):
            flush()
            skip_depth += 1
        if skip_depth:
            if END_SKIP_RE.match(line):
                skip_depth = max(0, skip_depth - 1)
            continue

        if not line:
            flush()
            continue
        if line.startswith("%"):
            continue
        if line.startswith("\\") and not line.startswith("\\noindent"):
            flush()
            continue
        buffer.append((line_no, raw_line))

    flush()
    return paragraphs


def build_ledger(tex_path: Path, paragraphs: list[Paragraph]) -> str:
    out: list[str] = []
    out.append("# Revision Ledger")
    out.append("")
    out.append(f"- Source file: `{tex_path}`")
    out.append("- Generated by: `easy-paper/scripts/latex_revision_sheet.py`")
    out.append("")

    current_section = None
    for paragraph in paragraphs:
        if paragraph.section_title != current_section:
            current_section = paragraph.section_title
            out.append(f"## S{paragraph.section_index:02d} {current_section}")
            out.append("")
        pid = f"S{paragraph.section_index:02d}.P{paragraph.paragraph_index:02d}"
        out.append(f"### {pid}")
        out.append("")
        out.append(f"- Location: lines {paragraph.start_line}-{paragraph.end_line}")
        out.append("- Paragraph role: TODO")
        out.append("- Current main claim: TODO")
        out.append("- Evidence IDs: TODO")
        out.append("- Reference style move: TODO")
        out.append("- Problems: TODO")
        out.append("- Revision strategy: TODO")
        out.append("- Post-revision logic: TODO")
        out.append("- LaTeX risk: TODO")
        out.append("")
        out.append("| Sentence ID | Original function | Issue | Evidence IDs | Source pattern, not wording | Revised sentence | Logic check | Risk |")
        out.append("|---|---|---|---|---|---|---|---|")
        sentences = split_sentences(paragraph.text)
        if sentences:
            for idx, sentence in enumerate(sentences, start=1):
                sid = f"{pid}.S{idx:02d}"
                clipped = sentence.replace("|", "\\|")
                if len(clipped) > 220:
                    clipped = clipped[:217].rstrip() + "..."
                out.append(f"| {sid} | TODO | TODO | TODO | TODO | {clipped} | TODO | TODO |")
        else:
            out.append(f"| {pid}.S01 | TODO | TODO | TODO | TODO | TODO | TODO | TODO |")
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tex_file", help="Path to the LaTeX file to inspect")
    parser.add_argument("--output", help="Where to write the revision ledger")
    args = parser.parse_args()

    tex_path = Path(args.tex_file).resolve()
    text = read_text(tex_path)
    paragraphs = collect_paragraphs(text.splitlines())
    ledger = build_ledger(tex_path, paragraphs)

    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(ledger + "\n", encoding="utf-8")
    print(ledger)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
